name: Sync to publicbroadcastarr as PR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout svtplayarr
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "a0a7"
          git config user.email "aw@a0.ax"

      - name: Add publicbroadcastarr as remote
        run: |
          git remote add target https://a0a7:${{ secrets.SYNC_TOKEN }}@github.com/a0a7/publicbroadcastarr.git
          git fetch target main

      - name: Resolve conflicts using "theirs"
        run: |
          git checkout main
          git rebase target/main || (git checkout --theirs .; git add .; git rebase --continue || true)

      - name: Push changes to a new branch in publicbroadcastarr
        run: |
          export BRANCH=sync-from-svtplayarr-$(date +%Y%m%d-%H%M%S)
          git push target HEAD:$BRANCH --force
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request on publicbroadcastarr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: "Sync from svtplayarr"
          title: "Sync from svtplayarr"
          body: "Automated PR to sync changes from svtplayarr."
          base: main
          head: ${{ env.branch }}
          repository: a0a7/publicbroadcastarr
